# -*- coding: utf-8 -*-
"""
Created on Tue Dec  3 20:00:29 2019

@author: gordon.garisch
"""

test = ['RT @WhiteHouse: President @realDonaldTrump just met with Prime Minister @JustinTrudeau of Canada. https://t.co/OqglFETMSE',
 'RT @WhiteHouse: President @realDonaldTrump just met with President @EmmanuelMacron of France—a partner of the United States in many key ven…',
 "RT @WhiteHouse: President Trump has been fighting for increased burden sharing by NATO members, and it's working. Over $130 billion in new…",
 'The United States of America supports the brave people of Iran who are protesting for their FREEDOM. We have under… https://t.co/zruahf60Bz',
 'RT @RepMattGaetz: Nancy Pelosi and other House Democrats overestimated the extent to which whatever allegations they’re making about the Uk…',
 "RT @RepMattGaetz: TONIGHT: I'll be on @seanhannity to discuss the latest on impeachment and the upcoming Judiciary hearings this week. TUNE…",
 'RT @willchamberlain: Looks like @DevinNunes and his team did some excellent work here\n\nThis is a robust defense of President Trump\n\nRead th…',
 'RT @DevinNunes: Great as always to be on with @JudgeJeanine https://t.co/XXIj69B81h',
 'RT @JudgeJeanine: Author of "The Plot against The President:The true story behind how Congressman Devin Nunes uncovered the biggest politic…',
 'RT @newtgingrich: In this week’s episode of my #podcast, I’m joined by Lee Smith, author of The Plot Against the President. I’ve tweeted qu…',
 'True! https://t.co/Mr1L4Vv3eA',
 "RT @RepMarkGreen: President Zelensky has repeatedly said there was no pressure to investigate @POTUS @realDonaldTrump's political rivals. A…",
 "RT @DailyMail: Ukraine's President Zelensky renews denial of a quid pro quo with Trump over military aid https://t.co/0OB3JQfJND",
 'Mini Mike Bloomberg has instructed his third rate news organization not to investigate him or any Democrat, but to… https://t.co/w1wsjiNu3a',
 'RT @CNBC: This year is shaping up to be one of the best ever for investors, with nearly every single asset class on track to finish 2019 in…',
 'Just landed in the United Kingdom, heading to London for NATO meetings tomorrow. Prior to landing I read the Republ… https://t.co/Y0em0Ks1CQ',
 'The Fed should lower rates (there is almost no inflation) and loosen, making us competitive with other nations, and… https://t.co/lujdrxG3bv',
 'Manufacturers are being held back by the strong Dollar, which is being propped up by the ridiculous policies of the… https://t.co/eoLE1xLQZe',
 'https://t.co/zlfV4MOkom',
 'RT @realDonaldTrump: Breaking News: The President of Ukraine has just again announced that President Trump has done nothing wrong with resp…',
 'RT @thehill: #BREAKING: Ukraine\'s Zelensky: I never talked to Trump about "position of a quid pro quo" https://t.co/1oFG9XWTmj https://t.co…',
 'Thank you to President Zelensky. Case over. The Do Nothing Democrats should finally go back to work! https://t.co/XrJSUsm9Wq',
 'RT @WhiteHouse: President @realDonaldTrump and @FLOTUS last traveled to the United Kingdom on a state visit in June 2019. https://t.co/6rwp…',
 'In the 3 decades before my election, NATO spending declined by two-thirds, and only 3 other NATO members were meeti… https://t.co/Jp7WB8B4HJ',
 'Great job by @RepDougCollins of Georgia over the weekend in representing the Republican Party, and myself, against the Impeachment Hoax!',
 'When Lisa Page, the lover of Peter Strzok, talks about being “crushed”, and how innocent she is, ask her to read Pe… https://t.co/UtXqn6GE4Q',
 'The Republican Party has NEVER been so united! This Impeachment Scam is just a continuation of the 3 year Witch Hun… https://t.co/W51pdKTM2g',
 'RT @FLOTUS: “The Spirit of America” is shining in the @WhiteHouse! I am delighted to share this beautiful exhibit of patriotism for all to…',
 'Not only did I see it @Doks_Art, I think it is fantastic. You are a wonderful artist, never give up your dream! https://t.co/LVVCUJz5CW',
 'Thank you to Great Republican @SenJohnKennedy for the job he did in representing both the Republican Party and myse… https://t.co/AkbWMNFmUD',
 'Thank you to Congressman Ben @Cline4Virginia for the Great remarks this morning on the illegitimate Impeachment Hoa… https://t.co/WCmMi7Q7Q2',
 'Heading to Europe to represent our Country and fight hard for the American People while the Do Nothing Democrats pu… https://t.co/GekUgvW7sj',
 'The Do Nothing Democrats get 3 Constitutional lawyers for their Impeachment hoax (they will need them!), the Republ… https://t.co/6Xh3iq7bSk',
 '“When the law enforcers turn out to be the law breakers, then we have totally upended the rule of law. Nobody is sa… https://t.co/tHJhCx6lQv',
 '“The Democrats don’t have any evidence, but they are still going to do it anyway. That’s the sham that’s going on h… https://t.co/SCgeO0pu5o',
 'Breaking News: The President of Ukraine has just again announced that President Trump has done nothing wrong with r… https://t.co/aTgsNTphK6',
 '“The United States has outperformed the rest of the world in an eye popping fashion. I don’t think we’ve seen numbe… https://t.co/4LUJ6DpgL2',
 '“The American people are going to see this for what it is. It is a political effort by the Democrats, and the Presi… https://t.co/7DFf3J8rEv',
 '“The process has been unfair. Republicans can’t even get their own witnesses. It gets me that Adam Schiff is not pu… https://t.co/DnIl5o1WoD',
 'U.S. Markets are up as much as 21% since the announcement of Tariffs on 3/1/2018 - and the U.S. is taking in massiv… https://t.co/JxjXnw8gll',
 '.....Reserve should likewise act so that countries, of which there are many, no longer take advantage of our strong… https://t.co/HTKwE89s8a',
 'Brazil and Argentina have been presiding over a massive devaluation of their currencies. which is not good for our… https://t.co/FpoeCsTlMQ',
 '“It is clear that there is none of the bipartisan support that Speaker Pelosi said for months was essential for Imp… https://t.co/Ae0wynG7k1',
 'RT @BLaw: The Trump administration is set to begin nationwide distribution of free HIV prevention medication to uninsured patients on Monda…',
 'RT @PARISDENNARD: “I’m so proud that President @realDonaldTrump has committed to ending the HIV epidemic in the next 10 years...the fact is…',
 '“Trump Economy Breaks Holiday Shopping Records.” @FoxNews',
 'Great writer and historian, Doug Wead, has written a true (not Fake News) account of what is going on in Washington… https://t.co/9IJCPlhrxK',
 '“Donald Trump was framed back in 2016.” @MariaBartiromo  100% correct, Maria, and we can never let this happen to another president again!',
 '....in America, community by community where we will eradicate AIDS in 10 years, program already started. American… https://t.co/LIRb5EfGWb',
 'On World AIDS Day, The First Lady and I express our support for those living with HIV/AIDS and mourn the lives lost… https://t.co/0wE8w4uHJD',
 '“Schiff’s impeachment hearings wasting time when Congress must do real work” https://t.co/4lb9bWrVRL',
 '“Trump did nothing impeachable, day-by-day review of all impeachment hearing testimony shows” @GreggJarrett https://t.co/QbFeEmWkTB',
 "“Sen. Tim Scott Says Trump 'Innocent,' 'No Way' Senate Convicts” https://t.co/P6ONkI8n0P",
 'RT @WhiteHouse: "The men and women of our military are totally loyal to our country. And every day I am President, America will always be t…',
 "RT @GOPChairwoman: Just 8 work days left on Congress' calendar this year.\n\nInstead of attacking @realDonaldTrump, Pelosi should work across…",
 'An incredible experience! https://t.co/n6BNQY6dIx',
 "RT @TeamTrump: One year ago today, President @realDonaldTrump signed the #USMCA with Canada and Mexico.\n\nIt now sits on Nancy Pelosi's desk…",
 'RT @VP: One year ago today, President @realDonaldTrump signed the #USMCA. While this Administration works FOR the American People, Speaker…',
 'RT @VP: President @realDonaldTrump’s deregulatory agenda unleashed American ingenuity and we are on path to becoming not just energy indepe…',
 "RT @WattersWorld: . @realDonaldTrump won't get the nomination, Trump won't win, Stock Market will tank, Russia Collusion...These are the st…",
 'RT @TeamTrump: President @realDonaldTrump will host a Keep America Great rally on Tuesday, December 10, at 7:00 pm (EST) at the Giant Cente…',
 'Nancy Pelosi won’t put it up for a vote. Has delayed it for 6 months. See you in #2020! https://t.co/lOrWm9u10r',
 'I will be representing our Country in London at NATO, while the Democrats are holding the most ridiculous Impeachme… https://t.co/UuVlxzywyZ',
 'Robert Johnson knows business &amp; politics. He also understands lowest African American Unemployment in U.S. history! https://t.co/NalNOFG53T',
 "RT @thehill: JUST IN: Top Judiciary Republican calls on committee to expand list of impeachment witnesses ahead of next week's hearing http…",
 'And the Do Nothing Democrats want to impeach President Trump? https://t.co/i3tPDJtuuA',
 'Thank you to @BuckMcNeely1 and Oliver North for the nice words and thoughts in an excellent interview. Best wishes!',
 "RT @CLewandowski_: Kamala Harris aide says in resignation letter: 'I've never seen staff treated so poorly' | TheHill. If this was the \u2066@re…",
 'RT @PressSec: Well said. There is so much work left do be done. Let’s move past this impeachment farce, follow the lead of @realDonaldTrump…',
 'https://t.co/AUoFQexhR4',
 'RT @SBAgov: #DidYouKnow small businesses create 2 out of every 3 net new jobs in the United States? 😮\n\nShow your support for entrepreneurs…',
 'Just returned to the United States after spending a GREAT Thanksgiving with our Courageous American Warriors in Afg… https://t.co/qdzzgdg91c',
 'RT @DiamondandSilk: .@DiamondandSilk talk about their experience at the Black Voices For Trump event along with the Itch of the week that n…',
 'I thought Newsweek was out of business? https://t.co/3ro4eSJloo',
 'HAPPY THANKSGIVING! https://t.co/7SGZnHindW',
 'RT @GOPChairwoman: Thank you for your sacrifice and service!\nhttps://t.co/dBj2wIgI2U',
 "RT @WhiteHouse: This Thanksgiving, we are thankful to all who wear our Nation's uniform, allowing us to celebrate in safety and peace. http…",
 'HAPPY THANKSGIVING! https://t.co/2GoxJEk6fN',
 'RT @WhiteHouse: "THEREFORE, I, DONALD J. TRUMP, President of the United States of America, by virtue of the authority vested in me by the C…',
 'RT @WhiteHouse: Congress broke for Thanksgiving late last week. Thanks to the far left’s impeachment stunt, the House has been effectively…',
 '95% Approval Rating in the Republican Party. Thank you!',
 'New Stock Market Record today, AGAIN. Congratulations USA!',
 'People now realize it is a Democrat Hoax! https://t.co/6O3lFa2wU7',
 'RT @EricTrump: What an amazing night in Florida! #USAUSAUSA https://t.co/EpPwXoCBOO',
 'https://t.co/11nzKwOCtU',
 'RT @GOPChairwoman: Overwhelmingly strong support for @realDonaldTrump in a DEM county in battleground Florida.\n\nHis supporters are already…',
 'GOD BLESS THE U.S.A.! #MAGA\nhttps://t.co/CYkQGHAgcx',
 'https://t.co/Jd7IbQBUvu',
 'THANK YOU FLORIDA! #KAG2020 https://t.co/mNB4KMEj9u',
 "“OMB Official: Ukraine Aid Held Up Because Other Countries Weren't Giving” https://t.co/nYwMq3M5SB",
 'https://t.co/1EYKod0tee',
 'RT @WhiteHouse: LIVE: President @realDonaldTrump Pardons the National Thanksgiving Turkey https://t.co/UjbVbghSiS',
 '...love to have Mike Pompeo, Rick Perry, Mick Mulvaney and many others testify about the phony Impeachment Hoax. It… https://t.co/PQorUuinkw',
 '...lawyer has already stated that I did nothing wrong. John Bolton is a patriot and may know that I held back the m… https://t.co/XCVTR2Od2l',
 'The D.C. Wolves and Fake News Media are reading far too much into people being forced by Courts to testify before C… https://t.co/8LsXGDsTbH',
 'RT @DailyCaller: President @realDonaldTrump signs the Women’s Suffrage Centennial Commemorative Coin Act which will direct the U.S. Treasur…',
 'RT @DailyCaller: Adam Schiff Challenger Jennifer Barbosa Attacks Him For Chasing Impeachment While Allegedly Ignoring Homeless People In Ca…',
 'RT @DailyCaller: The Tide Is Turning Against Democrats On Impeachment https://t.co/xpUwqz2JP1',
 'RT @DailyCaller: Poll: Independents Flip On Impeachment, Now Opposed After First Two Weeks Of Public Hearings. https://t.co/hjwicx0Pys',
 'When the Military rips down an old &amp; badly broken Border Wall in an important location, &amp; replaces it with a brand… https://t.co/5UwBsVacdG',
 'I will always protect our great warfighters. I’ve got your backs!',
 'Great job Heather! https://t.co/8OX8wkug4t',
 'RT @HeatherChilders: Is there a 2020 Democrat who can compete on the economy? - University of Maryland business professor @PMorici1 weighs…',
 'RT @JennaEllisEsq: As this sham continues, remember this is supposedly an impeachment hearing — not a personnel hearing, not a policy debat…',
 '“Poll shows Dems losing interest in Impeachment inquiry all across the board. These Polls are actually devastating… https://t.co/K1b9B05IEY',
 'RT @GOPChairwoman: Pelosi herself said impeachment must be “compelling,” “overwhelming,” and "bipartisan.”\n\nAfter 2 weeks of sham hearings,…',
 'RT @GeraldoRivera: As Democrats charge forward on #Impeachment of @realDonaldTrump despite certainty of defeat, don’t let them forget phony…',
 'RT @TeamTrump: President @realDonaldTrump will host a Keep America Great rally TOMORROW at 7:00 PM EST at @thebbtcenter in Sunrise, Florida…',
 'RT @WhiteHouse: President @realDonaldTrump met with Prime Minister @BoykoBorissov earlier today on measures to strengthen the strategic par…',
 "RT @EricTrump: Great job \u2066@realDonaldTrump\u2069 and \u2066@LaraLeaTrump\u2069! \n\nDonald Trump signs animal cruelty bill targeting 'heinous and sadistic'…",
 'RT @realDonaldTrump: “DOW, NASDAQ, S&amp;P 500 CLOSE AT RECORD HIGHS” https://t.co/q8IuuuUGjb',
 'https://t.co/Rya9MUlX1v',
 '“Democrats committed to impeaching Trump for no reason.” Will backfire into big 2020 Victory for Republicans! @IngrahamAngle',
 'RT @WhiteHouse: President Trump signed the Women’s Suffrage Centennial Commemorative Coin Act! \n\n@USTreasury will issue $1 coins commemorat…',
 'RT @WhiteHouse: President @realDonaldTrump just signed the Preventing Animal Cruelty and Torture (PACT) Act into law—which makes it a Feder…',
 '“DOW, NASDAQ, S&amp;P 500 CLOSE AT RECORD HIGHS” https://t.co/q8IuuuUGjb',
 'RT @WhiteHouse: Congratulations to all of the @NCAA National Champions! 🏆 https://t.co/9OIZQqiT5Z',
 'https://t.co/BETsNAWsNs',
 'Another new Stock Market Record. Enjoy!',
 '“The Democrats are getting hit and slammed on Impeachment. It is getting less and less popular by the day.” @kilmeade @foxandfriends',
 'Support for Impeachment is dropping like a rock, down into the 20’s in some Polls. Dems should now get down to work… https://t.co/O9sWK7ibHM',
 '“President Trump is facing a process which is unprecedented for its unfairness.” Sam Dewey',
 'RT @realDonaldTrump: Agnes, your great boy Ronald is looking down, very proud of you! https://t.co/BHPu6IIdAN',
 'RT @KatrinaPierson: “Trump 2020 baby!”\n\n@realDonaldTrump will win in 2020, and he’s going to do it with the help of millions of Black voter…',
 'RT @WhiteHouse: President @realDonaldTrump welcomed outstanding student athletes and coaches from all over the Nation to the White House fo…',
 'RT @GOPChairwoman: “That he is unconventional is not a bad thing for me. Heck, it’s why I voted for him.”\n\nFantastic read from @SalenaZito…',
 '....honors that he has earned, including his Trident Pin. Admiral and now Ambassador to Norway Ken Braithwaite will… https://t.co/rM0vnGCs87',
 '....contracting procedures were not addressed to my satisfaction. Therefore, Secretary of the Navy Richard Spencer’… https://t.co/wDkQrdlDG5',
 'I was not pleased with the way that Navy Seal Eddie Gallagher’s trial was handled by the Navy. He was treated very… https://t.co/bFwiFKQi9e',
 'Democrats going back to their Districts for Thanksgiving are getting absolutely hammered by their constituents over… https://t.co/IXzP5VLroK',
 '“The whole Russia thing was a Hoax, and the Ukraine thing is a Hoax, and the Democrats are a Joke. This is a disast… https://t.co/DaIU3HxznC',
 'The Impeachment Scam is driving Republican Poll Numbers UP, UP, UP! Thank you Shifty.',
 'RT @MZHemingway: The first phase of impeachment did not go well for Democrats. It needed to be a time when support for the inquiry and impe…',
 'RT @MZHemingway: @VanityFair "By massive margins, Independents say that the impeachment issue is \'more important to politicians than it is…',
 'This is a great and well reseached book on Justice K. The Ruth Marcus book is a badly written &amp; reseached disaster.… https://t.co/vS6EEFdMEj',
 'RT @RepWalorski: And yet, one thing remains the same: House Democrats have wanted to impeach the president since day one. These hearings ha…',
 'RT @HouseCommerce: As I have said before - no president has leaned in more than @realDonaldTrump on lowering drug costs for the American pe…',
 'Witch Hunt! https://t.co/CvZtyHMsGo',
 'RT @RoScarborough: Nunes to sue CNN, Daily Beast over ‘demonstrably false’ stories he sought dirt on Biden - https://t.co/MqPwlasYbK - @was…',
 'RT @GregGutfeldShow: Adam Schiff takes a Rorschach test. #Gutfeld https://t.co/khtdFVRHpv',
 'RT @GregGutfeldShow: Adam Schiff tries stand-up comedy. #Gutfeld https://t.co/8bu4cSHb9q',
 "RT @GregGutfeldShow: WATCH: Greg's latest monologue. #Gutfeld https://t.co/3nV60FCQ5g",
 "RT @marklevinshow: Here's a preview of tonight's Life, Liberty and Levin on Fox News at 8pm eastern. https://t.co/lhR6Uh8pXt",
 'RT @AndrewPollackFL: Michael Bloomberg’s accomplishments:\n\nBanning big gulp sodas\n\nBeing the worst NYC mayor after Bill de Blasio\n\nTrashing…',
 'RT @AndrewPollackFL: Wow! Thanks everyone for supporting Help Meadow Save the Day! \n\nIt’s almost in the top 50 sales ranking on Barnes &amp; No…',
 'RT @AndrewPollackFL: The California Supreme Court is the only piece of government in the state that has any common sense left.\n\nPresident T…',
 'RT @MZHemingway: Oh dear. Hunter Biden-linked company received $130M in special federal loans while Joe Biden was vice president https://t.…',
 'RT @WayneDupreeShow: This whole Ukraine thing is about to blow up in Dems face so big time.\n\nhttps://t.co/D668vbxzUA',
 'RT @PeteHegseth: Huge CONGRATS to new mom @JedediahBila &amp; hubby Jeremy! Welcome baby Hartley to the @foxandfriends family. So glad all is w…',
 'RT @BuckSexton: Simply mind boggling that here we are, heading into year 4 of the Trump presidency, in a time of tremendous American econom…',
 'RT @BuckSexton: Russia invaded eastern Ukraine,  picked off Crimea, and shot an airliner out of the sky killing hundreds of civilians *WHIL…',
 'RT @DonaldJTrumpJr: For perspective THIS X 1000!!! \nWonder why? https://t.co/Juz7piWvCH',
 'RT @BuckSexton: Be prepared for bureaucrats at FBI to claim sheer incompetence as their defense to whatever comes out of the Horowitz probe…',
 'RT @BuckSexton: People need to stop making Democrats look like a bunch of crazy Left wing extremists by quoting them and sharing their offi…',
 "RT @ByronYork: NPR reviews new Glenn Simpson book. Says Steele dossier 'found its way to news organizations.' Why obscure what happened? In…",
 'RT @SebGorka: What did Forrest Gump’s mama say about stupid people ? https://t.co/z1OSff5NqH',
 'RT @bdomenech: "By massive margins, Independents say that the impeachment issue is “more important to politicians than it is to me” (62% to…',
 'RT @DailyCaller: .@ewarren lies about the fact that she sent her kids to private school. \n\n“I read that your children went to private schoo…',
 'But I did nothing wrong. Read the Transcripts (2)! https://t.co/Ef9O5kOgrg',
 '100% Correct! https://t.co/VJfkmaraGV',
 'RT @RepRobertHurt: Great to have my brother @charleshurt join us for @LibertyU Convocation this week.\nhttps://t.co/mLM1hGn2gy',
 'Agnes, your great boy Ronald is looking down, very proud of you! https://t.co/BHPu6IIdAN',
 "RT @RealSaavedra: New RNC ad uses Democrats' own words on impeachment against them https://t.co/GDm8xgJ0wR",
 'Exclusive: Elise Stefanik Reflects on Her Two-Week Whirlwind https://t.co/5SownqVBuD',
 'RT @townhallcom: This whole thing is tearing our country apart. https://t.co/AW2lWvNRxM',
 'The Unspoken Truth: What Impeachment Exposed About Trump and 2020 https://t.co/pYTYBcD55I',
 'RT @KatiePavlich: Looking forward to “Adam Schiff tries to act angry” on the @greggutfeld show',
 'This is the real story behind the Do Nothing Democrats! https://t.co/4tPTICdSR1',
 'RT @LouDobbs: A tremendous week. @POTUS says he ‘wants’ a full senate trial following the dems’ disastrous impeachment hearings. @PressSec…',
 'RT @LouDobbs: Case Closed! @SaraCarterDC @CharlesHurt say the radical Dems have no case or evidence to impeach @POTUS. #MAGA #AmericaFirst…',
 'Too bad we didn’t have the G-7 here. I offered to pick up the entire cost, would have saved at least $35,000,000 fo… https://t.co/yNA3lYQPmF',
 'Polls have now turned very strongly against Impeachment, especially in swing states. 75% to 25%. Thank you!',
 'Nancy Pelosi, Adam Schiff, AOC and the rest of the Democrats are not getting important legislation done, hence, the… https://t.co/fMUhL1DArp',
 'Navy Seal Eddie Gallagher will be on @foxandfriends this morning at 7:30 A.M. Have no fear, all will end well for everyone!',
 'Pushed hard to have Apple build in USA! https://t.co/BRfXBkJdc2',
 'https://t.co/XexXL5HYRU',
 'https://t.co/x7ATRLwGpY',
 'https://t.co/iSzJDM7CZw',
 '95% Approval Rate in the Republican Party, a record! Thank you!',
 'Thank you Kevin for the nice words! https://t.co/DfY1V38EhD',
 '....Sondland said Trump told him. None of this will move the needle for anyone. And now Dems in Swing Districts hea… https://t.co/h5ysRHtCVn',
 '....ANY DIRECT EVIDENCE THAT PRESIDENT TRUMP DID ANYTHING IMPEACHABLE. No one heard him order a quid pro quo. No on… https://t.co/05oujkZc08',
 'NEW YORK POST EDITORIAL. “Worse Than Pointless. All those hours of televised testimony plainly failed on their anno… https://t.co/1XAuOFHyVk',
 'Daniel Cameron, who just won the A.G. race in the Great Commonwealth of Kentucky, is a young and very talented poli… https://t.co/l6Nw61LPHy',
 '.....Brennan, too. And the Whistleblower also worked for Susan Rice. It’s an understatement to say that this is a W… https://t.co/Kc4WtfYQbo',
 '“The Democrats dirty tricks have started this whole thing. The Whistleblower, the guy who took his case to Schiff’s… https://t.co/ufbUmLQFvs',
 'Joe Concha, The Hill: “In Emerson College Poll, Impeachment among independents, 49% Oppose, 34% Support. You see wh… https://t.co/bocPR9Om0g',
 'Adam Schiff will be compelled to testify should the Democrats decide, despite the fact that my presidential convers… https://t.co/bD2rqpRbSx',
 '“The support for Impeachment is not there. I think the Democrats will have to come up with a new game plan.” @jasoninthehouse @FoxNews',
 "RT @ByronYork: Schiff says when Republicans use phrase 'Russia hoax,' they are denying Russian interference. Untrue. Obvious fact: When Rep…",
 'RT @RepMarkMeadows: Potentially huge. Stay tuned... \n\n“Horowitz reportedly finds evidence FBI lawyer falsified FISA doc”\nhttps://t.co/RzSF3…',
 "RT @Jim_Jordan: “Jim Jordan says facts are on Trump's side after week of public impeachment hearings”\n\n@BretBaier https://t.co/gBPNYvYPjW",
 'RT @RepMarkMeadows: Wow - Impeachment way under water with independents. 49% oppose, only 34% support.\n\nThe American people see through thi…',
 'https://t.co/Mn4EJ7Jbh8',
 '...House Republicans are showing real LEADERSHIP and prepared to enact bipartisan solutions for drug prices. Do Not… https://t.co/YkzY7kPOKw',
 '...Pelosi and her Do Nothing Democrats drug pricing bill doesn’t do the trick. FEWER cures! FEWER treatments! Time… https://t.co/DPhFX0VKoO',
 '...While we had the first prescription drug price decrease in 50 years, Americans still pay far too much for drugs… https://t.co/1qy4kNPIg1',
 '.@SecAzar and I will soon release a plan to let Florida and other States import prescription drugs that are MUCH CH… https://t.co/KUCvUfA3JU',
 'Thank you to @senatemajldr Mitch McConnell and @GOPLeader Kevin McCarthy for their Great Leadership! There has neve… https://t.co/4armKSJjEo']